Repository simple-robot/simbot-component-qq-guild, pull requests merged in 2023-04, with the labels that each got.

#60 dev/feat/core_role
  build.gradle.kts
  buildSrc/src/main/kotlin/P.kt
  gradle.properties
  gradle/libs.versions.toml
  simbot-component-qq-guild-api/src/commonMain/kotlin/love/forte/simbot/qguild/QQGuildApiException.kt
  simbot-component-qq-guild-api/src/commonMain/kotlin/love/forte/simbot/qguild/api/QQGuildApi.kt
  simbot-component-qq-guild-api/src/commonMain/kotlin/love/forte/simbot/qguild/api/role/CreateGuildRoleApi.kt
  simbot-component-qq-guild-api/src/commonMain/kotlin/love/forte/simbot/qguild/api/role/ModifyGuildRoleApi.kt
  simbot-component-qq-guild-api/src/commonMain/kotlin/love/forte/simbot/qguild/model/Role.kt
  simbot-component-qq-guild-core-common/src/main/kotlin/love/forte/simbot/component/qguild/QGGuild.kt
  simbot-component-qq-guild-core-common/src/main/kotlin/love/forte/simbot/component/qguild/QGMember.kt
  simbot-component-qq-guild-core-common/src/main/kotlin/love/forte/simbot/component/qguild/QGRole.kt
  simbot-component-qq-guild-core-common/src/main/kotlin/love/forte/simbot/component/qguild/message/StandardMessageParsers.kt
  simbot-component-qq-guild-core-common/src/main/kotlin/love/forte/simbot/component/qguild/role/QGGuildRole.kt
  simbot-component-qq-guild-core-common/src/main/kotlin/love/forte/simbot/component/qguild/role/QGMemberRole.kt
  simbot-component-qq-guild-core-common/src/main/kotlin/love/forte/simbot/component/qguild/role/QGRoleCreator.kt
  simbot-component-qq-guild-core-common/src/main/kotlin/love/forte/simbot/component/qguild/role/QGRoleUpdater.kt
  simbot-component-qq-guild-core/src/main/kotlin/love/forte/simbot/component/qguild/internal/QGBotImpl.kt
  simbot-component-qq-guild-core/src/main/kotlin/love/forte/simbot/component/qguild/internal/QGGuildImpl.kt
  simbot-component-qq-guild-core/src/main/kotlin/love/forte/simbot/component/qguild/internal/QGMemberImpl.kt
  simbot-component-qq-guild-core/src/main/kotlin/love/forte/simbot/component/qguild/internal/role/BaseQGRole.kt
  simbot-component-qq-guild-core/src/main/kotlin/love/forte/simbot/component/qguild/internal/role/QGGuildRoleImpl.kt
  simbot-component-qq-guild-core/src/main/kotlin/love/forte/simbot/component/qguild/internal/role/QGMemberRoleImpl.kt
  simbot-component-qq-guild-core/src/main/kotlin/love/forte/simbot/component/qguild/internal/role/QGRoleCreatorImpl.kt
  simbot-component-qq-guild-core/src/main/kotlin/love/forte/simbot/component/qguild/internal/role/QGRoleUpdaterImpl.kt
  simbot-component-qq-guild-stdlib/build.gradle.kts
  simbot-component-qq-guild-stdlib/src/commonMain/kotlin/love/forte/simbot/qguild/internal/BotImpl.kt
Labels: 特性

#61 增加新的 `Unknown` 事件类型来解决未知事件无法处理的问题
  .github/workflows/test-branch.yml
  simbot-component-qq-guild-api/src/commonMain/kotlin/love/forte/simbot/qguild/event/Signal.kt
  simbot-component-qq-guild-api/src/commonTest/kotlin/ApiTest.kt
  simbot-component-qq-guild-api/src/commonTest/kotlin/QGMessageForSendingToFormDataTest.kt
  simbot-component-qq-guild-stdlib/src/commonMain/kotlin/love/forte/simbot/qguild/internal/BotImpl.kt
Labels: 特性

#63 Release: v3.0.0.0-alpha.5
  .changelog/v3.0.0.0-alpha.5.md
  .github/workflows/deploy-website.yml
  .github/workflows/publish-release.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/test-branch.yml
  README.md
  build.gradle.kts
  buildSrc/src/main/kotlin/P.kt
  gradle.properties
  gradle/libs.versions.toml
  simbot-component-qq-guild-api/src/commonMain/kotlin/love/forte/simbot/qguild/QQGuildApiException.kt
  simbot-component-qq-guild-api/src/commonMain/kotlin/love/forte/simbot/qguild/api/QQGuildApi.kt
  simbot-component-qq-guild-api/src/commonMain/kotlin/love/forte/simbot/qguild/api/Serializers.kt
  simbot-component-qq-guild-api/src/commonMain/kotlin/love/forte/simbot/qguild/api/role/CreateGuildRoleApi.kt
  simbot-component-qq-guild-api/src/commonMain/kotlin/love/forte/simbot/qguild/api/role/ModifyGuildRoleApi.kt
  simbot-component-qq-guild-api/src/commonMain/kotlin/love/forte/simbot/qguild/event/EventIntents.kt
  simbot-component-qq-guild-api/src/commonMain/kotlin/love/forte/simbot/qguild/event/Signal.kt
  simbot-component-qq-guild-api/src/commonMain/kotlin/love/forte/simbot/qguild/model/Role.kt
  simbot-component-qq-guild-api/src/commonTest/kotlin/ApiTest.kt
  simbot-component-qq-guild-api/src/commonTest/kotlin/QGMessageForSendingToFormDataTest.kt
  simbot-component-qq-guild-core-common/src/main/kotlin/love/forte/simbot/component/qguild/QGGuild.kt
  simbot-component-qq-guild-core-common/src/main/kotlin/love/forte/simbot/component/qguild/QGMember.kt
  simbot-component-qq-guild-core-common/src/main/kotlin/love/forte/simbot/component/qguild/QGRole.kt
  simbot-component-qq-guild-core-common/src/main/kotlin/love/forte/simbot/component/qguild/config/IntentsConfig.kt
  simbot-component-qq-guild-core-common/src/main/kotlin/love/forte/simbot/component/qguild/config/QGBotFileConfiguration.kt
  simbot-component-qq-guild-core-common/src/main/kotlin/love/forte/simbot/component/qguild/message/StandardMessageParsers.kt
  simbot-component-qq-guild-core-common/src/main/kotlin/love/forte/simbot/component/qguild/role/QGGuildRole.kt
  simbot-component-qq-guild-core-common/src/main/kotlin/love/forte/simbot/component/qguild/role/QGMemberRole.kt
  simbot-component-qq-guild-core-common/src/main/kotlin/love/forte/simbot/component/qguild/role/QGRoleCreator.kt
  simbot-component-qq-guild-core-common/src/main/kotlin/love/forte/simbot/component/qguild/role/QGRoleUpdater.kt
  simbot-component-qq-guild-core-common/src/test/kotlin/love/forte/simbot/component/qgguild/test/FileConfigTest.kt
  simbot-component-qq-guild-core/src/main/kotlin/love/forte/simbot/component/qguild/internal/QGBotImpl.kt
  simbot-component-qq-guild-core/src/main/kotlin/love/forte/simbot/component/qguild/internal/QGGuildImpl.kt
  simbot-component-qq-guild-core/src/main/kotlin/love/forte/simbot/component/qguild/internal/QGMemberImpl.kt
  simbot-component-qq-guild-core/src/main/kotlin/love/forte/simbot/component/qguild/internal/role/BaseQGRole.kt
  simbot-component-qq-guild-core/src/main/kotlin/love/forte/simbot/component/qguild/internal/role/QGGuildRoleImpl.kt
  simbot-component-qq-guild-core/src/main/kotlin/love/forte/simbot/component/qguild/internal/role/QGMemberRoleImpl.kt
  simbot-component-qq-guild-core/src/main/kotlin/love/forte/simbot/component/qguild/internal/role/QGRoleCreatorImpl.kt
  simbot-component-qq-guild-core/src/main/kotlin/love/forte/simbot/component/qguild/internal/role/QGRoleUpdaterImpl.kt
  simbot-component-qq-guild-stdlib/build.gradle.kts
  simbot-component-qq-guild-stdlib/src/commonMain/kotlin/love/forte/simbot/qguild/internal/BotImpl.kt
  website/docs/bot-config/_category_.json
  website/docs/bot-config/index.md
  website/docs/home.md
  website/docs/quick-start/_category_.json
  website/docs/quick-start/spring-boot.md
  website/docusaurus.config.js
  website/package-lock.json
  website/package.json
  website/src/css/JetBrainsMono-SemiBold.woff2
  website/src/css/custom.css
  website/src/css/iconfont.ttf
  website/src/pages/markdown-page.md
Labels: for-release

#64 doc: update spring-boot.md
  website/docs/quick-start/spring-boot.md
Labels: 文档, ignore-in-release

#65 为部分可分页的列表查询API增加直接创建flow的内联扩展
  README.md
  simbot-component-qq-guild-api/src/commonMain/kotlin/love/forte/simbot/qguild/api/member/GetGuildMemberListApi.kt
  simbot-component-qq-guild-api/src/commonMain/kotlin/love/forte/simbot/qguild/api/member/GetGuildRoleMemberListApi.kt
  simbot-component-qq-guild-api/src/commonMain/kotlin/love/forte/simbot/qguild/api/user/GetBotGuildListApi.kt
  simbot-component-qq-guild-core-common/src/main/kotlin/love/forte/simbot/component/qguild/role/QGGuildRole.kt
  simbot-component-qq-guild-core/src/main/kotlin/love/forte/simbot/component/qguild/internal/QGGuildImpl.kt
Labels: 特性

#67 支持精华消息相关API
  simbot-component-qq-guild-api/README.md
  simbot-component-qq-guild-api/src/commonMain/kotlin/love/forte/simbot/qguild/api/channel/pins/AddPinsMessageApi.kt
  simbot-component-qq-guild-api/src/commonMain/kotlin/love/forte/simbot/qguild/api/channel/pins/DeletePinsMessageApi.kt
  simbot-component-qq-guild-api/src/commonMain/kotlin/love/forte/simbot/qguild/api/channel/pins/GetPinsMessageApi.kt
  simbot-component-qq-guild-api/src/commonMain/kotlin/love/forte/simbot/qguild/model/PinsMessage.kt
  website/docusaurus.config.js
  website/src/pages/index.js
Labels: 特性

#71 core模块支持bot配置中有关timeout的配置
  simbot-component-qq-guild-core-common/src/main/kotlin/love/forte/simbot/component/qguild/config/QGBotFileConfiguration.kt
Labels: 特性

#72 支持 `"传递性"` 缓存
  simbot-component-qq-guild-core-common/src/main/kotlin/love/forte/simbot/component/qguild/QGChannelCategory.kt
  simbot-component-qq-guild-core-common/src/main/kotlin/love/forte/simbot/component/qguild/config/CacheStrategyConfig.kt
  simbot-component-qq-guild-core-common/src/main/kotlin/love/forte/simbot/component/qguild/config/QGBotComponentConfiguration.kt
  simbot-component-qq-guild-core-common/src/main/kotlin/love/forte/simbot/component/qguild/config/QGBotFileConfiguration.kt
  simbot-component-qq-guild-core/src/main/kotlin/love/forte/simbot/component/qguild/internal/QGBotImpl.kt
  simbot-component-qq-guild-core/src/main/kotlin/love/forte/simbot/component/qguild/internal/QGChannelCategoryImpl.kt
  simbot-component-qq-guild-core/src/main/kotlin/love/forte/simbot/component/qguild/internal/QGChannelImpl.kt
  simbot-component-qq-guild-core/src/main/kotlin/love/forte/simbot/component/qguild/internal/QGEventProcess.kt
  simbot-component-qq-guild-core/src/main/kotlin/love/forte/simbot/component/qguild/internal/QGGuildBotImpl.kt
  simbot-component-qq-guild-core/src/main/kotlin/love/forte/simbot/component/qguild/internal/QGGuildImpl.kt
  simbot-component-qq-guild-core/src/main/kotlin/love/forte/simbot/component/qguild/internal/QGMemberImpl.kt
  simbot-component-qq-guild-core/src/main/kotlin/love/forte/simbot/component/qguild/internal/event/QGAtMessageCreateEventImpl.kt
  simbot-component-qq-guild-core/src/main/kotlin/love/forte/simbot/component/qguild/internal/role/QGGuildRoleImpl.kt
  simbot-component-qq-guild-core/src/main/kotlin/love/forte/simbot/component/qguild/internal/role/QGMemberRoleImpl.kt
  simbot-component-qq-guild-core/src/main/kotlin/love/forte/simbot/component/qguild/internal/role/QGRoleCreatorImpl.kt
Labels: 特性

#74 Release: v3.0.0.0-alpha.6
  .changelog/v3.0.0.0-alpha.6.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/doc.yml
  .github/workflows/test-branch.yml
  README.md
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/P.kt
  gradle.properties
  gradle/libs.versions.toml
  kotlin-js-store/yarn.lock
  simbot-component-qq-guild-api/README.md
  simbot-component-qq-guild-api/build.gradle.kts
  simbot-component-qq-guild-api/src/commonMain/kotlin/love/forte/simbot/qguild/QQGuild.kt
  simbot-component-qq-guild-api/src/commonMain/kotlin/love/forte/simbot/qguild/api/channel/pins/AddPinsMessageApi.kt
  simbot-component-qq-guild-api/src/commonMain/kotlin/love/forte/simbot/qguild/api/channel/pins/DeletePinsMessageApi.kt
  simbot-component-qq-guild-api/src/commonMain/kotlin/love/forte/simbot/qguild/api/channel/pins/GetPinsMessageApi.kt
  simbot-component-qq-guild-api/src/commonMain/kotlin/love/forte/simbot/qguild/api/channel/schedules/CreateScheduleApi.kt
  simbot-component-qq-guild-api/src/commonMain/kotlin/love/forte/simbot/qguild/api/channel/schedules/DeleteScheduleApi.kt
  simbot-component-qq-guild-api/src/commonMain/kotlin/love/forte/simbot/qguild/api/channel/schedules/GetScheduleApi.kt
  simbot-component-qq-guild-api/src/commonMain/kotlin/love/forte/simbot/qguild/api/channel/schedules/GetScheduleListApi.kt
  simbot-component-qq-guild-api/src/commonMain/kotlin/love/forte/simbot/qguild/api/channel/schedules/ModifyScheduleApi.kt
  simbot-component-qq-guild-api/src/commonMain/kotlin/love/forte/simbot/qguild/api/channel/schedules/ScheduleRequestBody.kt
  simbot-component-qq-guild-api/src/commonMain/kotlin/love/forte/simbot/qguild/api/member/GetGuildMemberListApi.kt
  simbot-component-qq-guild-api/src/commonMain/kotlin/love/forte/simbot/qguild/api/member/GetGuildRoleMemberListApi.kt
  simbot-component-qq-guild-api/src/commonMain/kotlin/love/forte/simbot/qguild/api/user/GetBotGuildListApi.kt
  simbot-component-qq-guild-api/src/commonMain/kotlin/love/forte/simbot/qguild/model/Announces.kt
  simbot-component-qq-guild-api/src/commonMain/kotlin/love/forte/simbot/qguild/model/Member.kt
  simbot-component-qq-guild-api/src/commonMain/kotlin/love/forte/simbot/qguild/model/MessageAudited.kt
  simbot-component-qq-guild-api/src/commonMain/kotlin/love/forte/simbot/qguild/model/PinsMessage.kt
  simbot-component-qq-guild-api/src/commonMain/kotlin/love/forte/simbot/qguild/model/Schedule.kt
  simbot-component-qq-guild-core-common/README.md
  simbot-component-qq-guild-core-common/src/main/kotlin/love/forte/simbot/component/qguild/QGChannelCategory.kt
  simbot-component-qq-guild-core-common/src/main/kotlin/love/forte/simbot/component/qguild/config/CacheStrategyConfig.kt
  simbot-component-qq-guild-core-common/src/main/kotlin/love/forte/simbot/component/qguild/config/QGBotComponentConfiguration.kt
  simbot-component-qq-guild-core-common/src/main/kotlin/love/forte/simbot/component/qguild/config/QGBotFileConfiguration.kt
  simbot-component-qq-guild-core-common/src/main/kotlin/love/forte/simbot/component/qguild/role/QGGuildRole.kt
  simbot-component-qq-guild-core/README.md
  simbot-component-qq-guild-core/src/main/kotlin/love/forte/simbot/component/qguild/internal/QGBotImpl.kt
  simbot-component-qq-guild-core/src/main/kotlin/love/forte/simbot/component/qguild/internal/QGChannelCategoryImpl.kt
  simbot-component-qq-guild-core/src/main/kotlin/love/forte/simbot/component/qguild/internal/QGChannelImpl.kt
  simbot-component-qq-guild-core/src/main/kotlin/love/forte/simbot/component/qguild/internal/QGEventProcess.kt
  simbot-component-qq-guild-core/src/main/kotlin/love/forte/simbot/component/qguild/internal/QGGuildBotImpl.kt
  simbot-component-qq-guild-core/src/main/kotlin/love/forte/simbot/component/qguild/internal/QGGuildImpl.kt
  simbot-component-qq-guild-core/src/main/kotlin/love/forte/simbot/component/qguild/internal/QGMemberImpl.kt
  simbot-component-qq-guild-core/src/main/kotlin/love/forte/simbot/component/qguild/internal/event/QGAtMessageCreateEventImpl.kt
  simbot-component-qq-guild-core/src/main/kotlin/love/forte/simbot/component/qguild/internal/role/QGGuildRoleImpl.kt
  simbot-component-qq-guild-core/src/main/kotlin/love/forte/simbot/component/qguild/internal/role/QGMemberRoleImpl.kt
  simbot-component-qq-guild-core/src/main/kotlin/love/forte/simbot/component/qguild/internal/role/QGRoleCreatorImpl.kt
  simbot-component-qq-guild-stdlib/README.md
  website/README.md
  website/docs/quick-start/api.md
  website/docs/quick-start/simbot-core.md
  website/docs/quick-start/spring-boot.md
  website/docs/quick-start/stdlib.md
  website/docusaurus.config.js
  website/src/css/custom.css
  website/src/pages/index.js
Labels: for-release

#75 `QGBot.guildCount` 的结果默认调整为 `-1`
  simbot-component-qq-guild-core-common/src/main/kotlin/love/forte/simbot/component/qguild/QGBot.kt
Labels: 缺陷
